### ISSUE TITLE
Updating network requires refreshing Console to connect

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-desktop#262]
## Tasks 

- [ ] Implement popup to explain what you need to do after updating a network e.g. "Updating the network will lose your existing wallet connections. Reset your wallet app to continue..."
- [ ] Talk to Matt about how to handle this in the dapp front end (if anything)

## Software information
Build info:
- Version: 0.2.1

**Tips:** You can get this information from the window located under the `File > About Vegawallet`.

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered
When updating a network config by overwriting an existing network with new config via URL, you need to disconnect from fairground console (v1 & v2), and the desktop wallet in order to get the apps to work with the correct nodes (and stop the DW from crashing).

# Expected behaviour
Updating network details in the wallet should automatically restart the wallet service and ask you to reconnect your wallet in the dApps. 

# Evidence
see comment below

**Comment by pennyandrews** [comment]
Even if the behaviour needs to stay like this we can manage user expectations better in the notifications around it
