### ISSUE TITLE
Consolidate journey through app features

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#269]
## The Chore

Consolidating new and existing features and navigation into one coherent flow - based on current priorities and re-using as many existing UI components as much as possible

## Acceptance criteria

- [ ] All existing features still work (but could be in a different way - this might impact tests)
- [ ] No new features have been added
- [ ] I can read some brief copy at the top of each view that explains what I'm looking at / need to do
- [ ] The app uses a consistent pattern for copying key elements i.e. IDs, signed messages etc.

## Tasks

- [ ] Agree a wallet Zoom day / time
- [ ] Cal and Botond to work through each step together designing changes in the browser (to ensure minimal code changes with max impact)
- [ ] Add / improve the copy relating to tainting/ed keys (notes below)
- [ ] Add / improve copy around message signing (notes below)
- [ ] Improve how you copy signed messages (notes below)
- [ ] Developer
- [ ] Review
- [ ] Test

## Tainting/ed keys copy notes

- Correct spelling mistakes "tained", and no explanation as to what tainted means.
- Once you have tainted it you can't use it to sign a transaction
- Any terminology would need to be changed end to end i.e. through the api, docs etc. "Taint" is common but may want to be reviewed ... e.g. mark as insecure
- Taint a key is to say that a key is not safe to use any more i.e. it has been compromised in some way or you don't want to use it for some other reason i.e. attached to real profile - for privacy

![image](https://user-images.githubusercontent.com/47143694/194308922-6417ed54-9a18-4cc4-a452-d1872b008a52.png)

## Message signing copy notes

We need to explain what signing a message is / is for so that I don't confuse it with signing a transaction
- I can understand the purpose of signing a message, how it can be used inside the wallet app E.g. Signing a message can be used to verify your identity by providing a verifiable link for a given public key.
- We've considered what's in docs / is there a gap there and filled it

![image](https://user-images.githubusercontent.com/47143694/194309475-f00558a4-db28-40c9-a470-70b8dc5a89b8.png)

## Copy signed message notes

The result of the signed message looks like a clickable link - instead the link should have a copy icon beside it.

![image](https://user-images.githubusercontent.com/47143694/194310194-74415a18-aa4c-46fe-bdf7-8d5da239e748.png)

The message is underlined, presumably to say 'Hey, you can interact with me'. But underlining to 👴 me says 'Click me to go somewhere'. The former is true, but I think it would be clearer by not underlining it and either having a separate button that was clearer, or... something else that @campbellssource can consider.
