### ISSUE TITLE
Identify and prioritise opportunities to improve the UX and visual design of the existing desktop wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#300]
## Story

As Vega
I want to identify opportunities to improve the UX and visual design of the existing desktop wallet
So that I can prioritise effectively

## Tasks

- [x] Review the current UX and sketch improvements (utilising any work that has already been done)
- [ ] Review the current visual design and mock up improvements (utilising what has already been done for brand and console)
- [ ] Workshop to review, refine and prioritise
- [ ] Write user stories for the backlog
- [ ] Sense check priorities with ELT, Barney and Ramsey
