### ISSUE TITLE
Change wallet name

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#316]
## Story

As a user
I want to be able to change my wallet name
So that I can correct a mistake or rename according to whatever organisational approach I'm taking

## Acceptance Criteria

- [ ] I can change the name of an existing wallet

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

<img width="1523" alt="Screenshot 2022-10-31 at 12 53 18" src="https://user-images.githubusercontent.com/46783148/199012382-b54223bb-9ad4-4e2f-acef-75d863a80b2c.png">

**Comment by ckpringle** [comment]
To check when available (part of backend backlog)
