### ISSUE TITLE
Explain what signing a message is in the UI

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#319]
## Story

As a wallet user
I want to understand what signing a message 
So that I don't confuse it with signing a transaction

## Acceptance Criteria

- [ ] I can understand the purpose of signing a message, how it can be used inside the wallet app E.g. Signing a message can be used to verify your identity by providing a verifiable link for a given public key.
- [ ] We've considered what's in docs / is there a gap there and filled it

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="1133" alt="Screenshot 2022-09-23 at 16 23 56" src="https://user-images.githubusercontent.com/46783148/191996396-3dc4e092-65d4-4602-97da-fc29e4724ac3.png">

**Comment by pennyandrews** [comment]
Now covered in https://github.com/vegaprotocol/vegawallet-desktop/issues/269

**Comment by ValentinTrinque** [comment]
This is done.
