### ISSUE TITLE
Approve change in permissions (Desktop Wallet)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#320]
## Story

As a user with a wallet without permission to share my public keys
I want to be asked when I'm connecting my wallet to a dapp, to change my permissions and do so there and then
So that I don't have to go and find permissions and start all over

## Acceptance Criteria

- [ ] I am informed I need to update my permissions to allow dapp name to see all my public keyes
- [ ] I can enter my password straight away to update my permissions to this wallet and complete connection with the dapp

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="603" alt="Screenshot 2022-09-23 at 16 31 17" src="https://user-images.githubusercontent.com/46783148/191997912-bd5464cb-08f0-4272-abb0-cc3281e30a1f.png">

**Comment by ckpringle** [comment]
Blocked dependant on the v2 integration
