### ISSUE TITLE
Connect to a tainted key

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#322]
## Story

As a user 
I want to be warned when I attempt to connect a dapp to a tainted key 
So that I understand why it's not going to work and can do something about it 

## Acceptance Criteria

- [ ] There is a description / notification when trying to connect to a tainted key 
- [ ] I can see some signposting to help me untaint it if I want to OR connect with a different key

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by ValentinTrinque** [comment]
This won't be possible as tainted keys are removed from the list of keys you can sign with.
