### ISSUE TITLE
Use "metadata" (or "labels"?) to sort and filter keys

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#323]
## Story

As a user
I want to be able to sort my keys based on my mental model of how each is being used
So that I can easily find the key(s) I'm looking for

## Acceptance Criteria

- [ ] We've updated the "add metadata" view to make it clear what this is for, and the states of the fields (are they labels, editable etc) including what we call this (remember this also includes the key name)
- [ ] We've rolled out any change in terminology wherever it exists
- [ ] I can sort and filter my list of keys using the metadata I have created 
- [ ] There is a way to understand how items appear in the filter / sort lists i.e. the labels you have created on your keys

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
