### ISSUE TITLE
Handle wallet version and network incompatibility

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#324]
## Story

As a user
I want to understand if / when my desktop wallet version is not supported by the network I am connecting to and what I can do about it 
So that I can connect successfully 

(There will be a brief period of time where Fairground and Mainnet networks are compatible with different versions of the desktop wallet app.)

## Acceptance Criteria

- [ ] When the network version is newer than the wallet: If I'm using a wallet app version that is not compatible with the network I have connected to (determined by the network configuration and nodes) - I am informed that I need to change version of the desktop wallet app e.g. Mainnet is running Vega version 1.32 - this app is running an older version 1.31 and no longer compatible. [Download Desktop Wallet version 3]
- [ ] When the wallet version is newer than the network the user is prompted to import a new network configuration. "The network you are using is outdated, import the new network configuration here (link to network settings screen in app) 

## Tasks

- [x] Catch up with Valentin to figure out how we can tell if an imported network is compatible with the desktop wallet version
- [x] Consider what is shown on the dapp (connect wallet UI for example), what is shown in the wallet app itself and supporting information on the website and docs
- [ ] Enable backend to share version compatibility + which version will work for each desktop release
- [x] Sketch copy / interaction
- [ ] Team and stakeholder review
- [ ] Visual Design (if needed)
- [ ] Develop
- [ ] Review
- [ ] Test

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/199006894-3e7a0e00-6630-437c-91c5-3d8540fa5e27.png)

~~Wallet version in desktop wallet app~~

~~When creating a wallet there is a field "Wallet version" which is a bit confusing as to what it means since this wallet is v0.1.1 and then it says 2 there, some context explaining what it is, e.g. (?) with popup info field.~~

![image](https://user-images.githubusercontent.com/47143694/194311071-8facf5ca-5a97-4aa7-9ec2-1b37c76e69e5.png)
Seen in build version: 0.1.1

~~Matt commented "Do we think its safe to remove this field entirely? As I understand it's likely to never change going forward? How many users do we think have the old version and what is the upgrade path for those users?"~~

**Comment by ckpringle** [comment]
Previously prompted user to download when there is a new release but we don't want the user to update every time while there are breaking changes, we want the user to use the wallet app version that  works with the network version.
