### ISSUE TITLE
Wallet connections

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#326]
## Story

As a user
I want to understand which third parties my wallet is connected to 
So that I can verify what I am connected to successfully

## Acceptance Criteria

- [ ] I can see which third parties have permissions to read my keys 

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/197397866-61748939-ece8-4148-8ac9-9155505e7b7f.png)

Miro link https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764536659641443&cot=14

**Comment by ValentinTrinque** [comment]
There are two things here.

Auditing where a key is used, and which third-party application is currently connected to the wallet.

These are 2 different things. Could you elaborate which case you are refereing to ?

**Comment by ckpringle** [comment]
Added a sketch @notbot00
