### ISSUE TITLE
Terminate a connection between a third party and a wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#327]
## Story

As a user
I want to disconnect my wallet (all keys) from certain sites 
So that I can manage my connections from one place

## Acceptance Criteria

- [ ] I can see my list of connections with the option to close
- [ ] I can "close the session" with a third party
- [ ] When I do so, I am warned of the implications e.g. are you sure you want to disconnect? You may lose (third party site) functionality

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/197397917-8c89e3f9-a519-4700-a900-ed75ce90381c.png)

Miro link https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764536659641443&cot=14

**Comment by ValentinTrinque** [comment]
Not sure I understand.

Do you want to be able to remove access to a key for certain third-party application ?

Or...

Do you want to be able end a live connection of a third-party app to the wallet ?

**Comment by ValentinTrinque** [comment]
@notbot00 We just need to call `admin.close_connection` for that.
