### ISSUE TITLE
View transactions from this session v2 only

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#346]
As a user
I can see a list of all complete transactions for each key pair in my wallet (from my current session)
So that I can understand what has happened and trouble shoot if something unexpected has happened

## Acceptance Criteria

- [ ] I can view a list of all complete transactions for the current key pair that have taken place this session 
- [ ] I can click on an individual transaction to view the transaction details in Block Explorer 
- [ ] I can click on a link to view a list of all of my transactions (party details view for my wallet) in Block Explorer  
- [ ] When I click on a link to a view in block explorer I am taken to the relevant block explorer app for the network I am currently connected to in the desktop wallet  

## Sketch 

![Image](https://user-images.githubusercontent.com/46783148/197398005-bef10c71-a9c5-450f-9025-8d4267e8def1.png)

## Tasks

- [ ] Sketch what's possible once we have visibility of the data we can return
- [ ] Design (if needed)
- [ ] Develop
- [ ] Review
- [ ] Test

## Background 

From Barney - It would be cool if the wallet showed a list of recent transactions and linked to the block explorer for these. Would aid debugging and learning and help connect together the various front ends and apps.
