### ISSUE TITLE
Improve AC coverage of wallet desktop app (e2e tests)

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-desktop#478]
## The Chore

We need to improve Acceptance criteria coverage of wallet-desktop app. We should use https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md for that.

## Tasks

- [x] Cross check AC that are already covered by our tests.
- [x] Define ACs that can be covered by additional tests.
- [x] Add UI tests for defined ACs. (in https://github.com/vegaprotocol/vegawallet-ui repo)
- [x] Add E2E tests for defined ACs.

**Comment by radoslaw-szpiech** [comment]
Quick summary of investigating AC coverage - https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md  ACs are split into UI and E2E groups:
- 3 ACs out of our scope - they relate to [Vega.xyz/wallet](http://vega.xyz/wallet) page and possibility to download latest version of wallets
- 28 E2E ACs, from which 15 are already covered. 13 that are left:
    - 2 are easy wins, few lines of code
    - 7 are related to Dapps connection/transactions which is difficult to cover at the moment by Cypress tests.
    - 4 needs some further investigation
- 39 UI ACs from which 7 are already covered already by E2E tests with following comments
    - These 7 are duplicated in UI and E2E, as they are more UI tests, but they are already covered in E2E so numbers don’t match. It will be decided if they should be moved or stay, or covered in both places during implementation phase.
    - There are few other duplicates (UI & E2E) as some verification should be done in UI, but the flow should be covered in e2e.
    - Lots of them are transaction details which are far more easier to be mocked and verified in UI than E2E

**Comment by radoslaw-szpiech** [comment]
There are few ACs left regarding Transactions, which implementation is currently under development. I will create separate issue for that.
