### ISSUE TITLE
Fix desktop-wallet interactions testability

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-desktop#479]
## The Chore

Currently we are not testing interactions (e.g. transactions sent from dapps), as it causes a lot of troubles in cypress. We need to find a way to make it possible to test.

## Tasks

- [ ] Investigate to find a reason of issues.
- [ ] Fix the issues on desktop-wallet side if found any by previous step.
- [ ] Verify cypress possibility to overcome the issues.
- [ ] Verify other tools possibility to overcome the issues (Playwright).

**Comment by radoslaw-szpiech** [comment]
It's done in `vegawallet-ui` repo. We can trigger and test every interaction flow there.
