### ISSUE TITLE
Improve clarity of transaction details

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-desktop#480]
## Story

As a vega wallet user
I want the purpose, status, and details of transactions to be clearly evident 
So that I can recognise transactions I initiated, and discern the outcome

## Acceptance Criteria

- [ ] I can discern the most important details of each transaction at a glance
- [ ] All transaction types are catered for, e.g. with a unique layout, including unique fields in the body of the view, not as raw JSON
- [ ] I do not have to understand JSON to discern any detail of a transaction
- [ ] I can find and view the raw JSON if I wish

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- At the time of writing, crucial transaction details are only shown in raw JSON, not formatted in a readable manner, nor brought to the forefront. This makes it difficult to review a transaction, understand its purpose, and (where applicable) decide if it should be approved.
- We should reconsider the information architecture and visual design of this view.
- Some platforms offer a "rich/raw" toggle, or tabs, to switch between a nicely formatted summary, and a less readable but comprehensive printout of all transaction data. We should consider offering the same.
