### ISSUE TITLE
Show event log and hash in transaction details

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-desktop#487]
## Story

As a vega wallet user
I want to know what stage an ongoing transaction is at, and how completed (approved, rejected, failed) transactions reached that state
So that I can keep track, and troubleshoot issues if they arise

## Acceptance Criteria

- [ ] I can see a live log of events, as they happen, in the transaction details view
- [ ] [Optional:] I can expand and collapse the event log, since it is supplementary information
- [ ] In the event log:
  - [ ] Success messages are green
  - [ ] Error messages are red
  - [ ] The selected node is highlighted (e.g. in bold text)
- [ ] I can find the transaction hash in the transaction details view, when it is available

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] [Optional:] Visual Design for expanding/collapsing elements in wallet
- [ ] Team review
- [ ] Implementation
- [ ] Share with team for QA

## Sketch
From [the Miro artboard](https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764545848004603&cot=14). We propose to use the same component (or style) as the "transaction details" for the event log.

![image](https://user-images.githubusercontent.com/1080322/218730211-83b8a775-6af4-4906-beb5-feeacb2af494.png)

## Additional details / background info
- Parent ticket: https://github.com/vegaprotocol/vegawallet-ui/issues/74
- Sibling tickets:
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/488
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/489

**Comment by ckpringle** [comment]
@ckpringle to get the latest from Neil on this
