### ISSUE TITLE
Central transaction log

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-desktop#488]
## Story

As a vega wallet user
I want to easily find my recent and ongoing transactions
So that I can discover the status and outcome of transactions if I missed it elsewhere

## Acceptance Criteria

- [x] I can find a single list of all transactions, completed and ongoing, from all keys and wallets, from my current desktop session and network 
- [x] If I switch network, transactions list changes to show the transactions for that network
- [x] I can click a transaction in the list to see the transaction details 
- [x] I can navigate between the transaction list and wallet list (tabs)
- [x] I can find my way to the complete transaction history for that key on block explorer
- [x] I can find my way to the transaction on block explorer
- [ ] #695
- [x] There is an empty state when there are no transactions for this session

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design for:
  - [x] in-app navigation
  - [x] visual device to indicate activity in the transaction tab
  - [x] transaction tab
  - [x] transaction detail changes to include links
- [x] Team review
- [x] Implementation (including implementing the UI toolkit into this view)
- [x] Team QA

## Design 
https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2231%3A8689&t=7BWvxgsCdORyvNNT-0

![Image](https://user-images.githubusercontent.com/46783148/223457978-64b6b821-f465-40d0-bd29-246e6fd89d2b.png)

## Sketch
![image](https://user-images.githubusercontent.com/1080322/218734754-f76261e6-6685-4248-929d-9dac5ebc5880.png)

The layout of the transaction tab is based on the transaction component which can be found in _Wallet → Key → View Transactions_:
![image](https://user-images.githubusercontent.com/1080322/218736104-2abd24cc-164a-4338-9527-896d9d99bc2f.png)

## Additional details / background info
- Parent ticket: https://github.com/vegaprotocol/vegawallet-ui/issues/74
- Sibling tickets:
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/487
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/489

**Comment by ckpringle** [comment]
@ckpringle to add a way to see which network each transaction was on

**Comment by joellecharlotte** [comment]
Transaction Detail attached and [in FIgma here](https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2552%3A2643&t=2I4grZMzpe6eEgSB-1) ↳. Two options for displaying the error, could use the inline notification TBD

<img width="3023" alt="Transaction Detail" src="https://user-images.githubusercontent.com/113684458/225267651-73f33d7f-e8a5-4c47-90d7-300f16d01b14.png">
