### ISSUE TITLE
Report transaction status changes with toasts

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-desktop#489]
## Story

As a vega wallet user
I want the desktop app to tell me when transactions I authorised complete or fail
So that I can take next steps (like returning to the app where I initiated it, or troubleshooting)

## Acceptance Criteria

- [ ] I am notified when an ongoing transaction changes status, to "in progress", "approved", "failed", or "rejected"
- [ ] I can navigate from that notification to full details of the transaction

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Determine how to import toast styles from asset library
- [ ] Determine all states for toasts, and copy for each state
  - [ ] For a fail state, what are all the possible error messages? Will they all fit in a toast component?
- [ ] Team review
- [ ] QA with team

## Sketch
![image](https://user-images.githubusercontent.com/1080322/218742119-90826e89-d1db-4cd3-a00e-67ca4782b9a9.png)

## Additional details / background info
- Parent ticket: https://github.com/vegaprotocol/vegawallet-ui/issues/74
- Sibling tickets:
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/488
  - https://github.com/vegaprotocol/vegawallet-desktop/issues/487
