### ISSUE TITLE
Combine Service and App configuration into Settings

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vegawallet-desktop#509]
## The Chore

Combine Service and Application Settings into one 'view' where the user can find and update settings for the service and the app in a single place.

## Acceptance criteria 
- [ ] There is a way to see and edit service settings 
- [ ] I can get to it from the setting tab 
- [ ] Individual settings e.g. Token expiry are only visible if they exist in the backend

## Tasks

- [ ] Sketch 
- [ ] Design 
- [ ] Implement 
- [ ] Test

## Sketch 

<img width="1394" alt="Screenshot 2023-03-14 at 14 09 21" src="https://user-images.githubusercontent.com/46783148/225027759-cf2215a0-3d06-42f1-bc42-1d23570ae2b1.png">

## Background / details

Service settings:

- Port
- Service log level
- Token expiry time (show if the data is there but read only, hide otherwise)

In https://github.com/vegaprotocol/vegawallet-desktop/pull/505 we introduced two new handlers to retrieve / update service specific settings. We need to figure out a place where we can display them on the UI, and allow the user to update the parts which make sense updating.

**Comment by joellecharlotte** [comment]
Here is the new Settings screen with App Settings and Service. [Figma link](https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2563%3A3230&t=2I4grZMzpe6eEgSB-1) ↳ 

<img width="2397" alt="Settings" src="https://user-images.githubusercontent.com/113684458/225296334-0775ee36-cfd6-44c6-aa6a-5c87f1d3b890.png">
