### ISSUE TITLE
Improve error messaging if VegaWallet directory is deleted

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-desktop#524]
## Description

If vegahome directory is suddenly missing, error is shown that cannot be avoided. However, if directory exists, but it's completely empty there is no problem - app will create some default network information during startup. 

## Steps to Reproduce

1. Run the app, set some vegahome aka Wallet directory
2. Close the app
3. Remove directory described in vegahome
4. Run the app
5. Error 

## Tasks 
- [ ] Write improved error message to explain something like " are you sure that file still exists have you manually changed the configuration " 
- [ ] Provide the user with a way to solve the problem
- [ ] Implement in the backend 

## Screenshots

![Screenshot 2023-02-22 at 13 53 39](https://user-images.githubusercontent.com/24473278/220634974-ff038d8e-3cca-4bf0-804e-c6734ea961f0.png)

## Background 

Previously discussed expected behaviour

Option A: (easiest one) - if vegahome directory is not found during startup, it should be created with default content (as it is done with empty vegahome directory)
Option B: App settings should be opened, with info that vegahome directory is not found with option to create one or change vegahome.

## Additional context

It's different case than describing non-existing directory in app settings and saving changes.
