### ISSUE TITLE
Visual representation of the number of steps and transitions between transactions

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#540]
## Story

As a user
I want to understand how many steps / interactions there are as part of this transaction
So that I am not surprised when there are multiple requests made one after the other

## Acceptance Criteria

- [ ] The number of interactions and number each interaction represents comes is technically available
- [ ] I can see that there will be more than one interaction i.e. there is a counter or visual progress bar
- [ ] I can see how many steps there will be
- [ ] I can see when I have moved from one interaction to the next i.e. the counter counts up or the progress bar moves along 
- [ ] There is an appropriate transition between one stage and another e.g. fade delay

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch (examples)

<img width="651" alt="Screenshot 2023-03-01 at 18 57 00" src="https://user-images.githubusercontent.com/46783148/222377817-10b54805-44a5-4009-ac41-374deb8688ab.png">
