### ISSUE TITLE
Ability to "try again" when a network connection error has occurred 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#571]
## Story

As a user
I want to quickly try to submit my transaction again without needing to go back to the dapp and start again 
So that I can get on with my trade

## Acceptance Criteria

- [ ] When a network error has occurred i.e. wallet has lost a connection to the network for whatever reason, there is a way to "try again" from the wallet error message without having to resubmit the transaction request from the dapp
- [ ] If the problem is a node is down, wallet will try to find another node to resubmit to 
- [ ] I can see how many nodes have been tried to complete the transaction
- [ ] If we've exhausted all nodes, there is a way to see that in the UI and there is a way to change nodes manually e.g. a link from there

## Tasks

- [ ] Explore and sketch how to make this possible considering the information the dapp will need from the wallet and the information the wallet will need to store in case of this happening
- [ ] Team and stakeholder review
- [ ] Implement solution
- [ ] Team review
- [ ] Etc.
