### ISSUE TITLE
Active key connections

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#586]
To decide - option 1, permissions as is, or option 2, revisiting permission management making it a bit simpler.

## Story

As a user
I want to see which keys are currently connected and visible to my connections
So that I can manage them quickly e.g. disconnect, update permissions

## Acceptance Criteria

- [ ] I can easily see the keys a dapp connection has access to within my wallet in the context of all my connections
- [ ] I can still manage permissions to update which keys the dapp has access to for that wallet
- [ ] I can see individual connections per key 

## Sketches 
<img width="1967" alt="Screenshot 2023-03-28 at 17 52 29" src="https://user-images.githubusercontent.com/46783148/228312309-3bc34c16-4860-4e41-9108-7adff591ff4a.png">

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
Some overlap https://github.com/vegaprotocol/vegawallet-desktop/issues/587
