### ISSUE TITLE
Add key to existing connection

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#587]
## Story

As a user 
I want to be able to easily add my new key to an existing connection
So that I can "get using" the key as quickly and easily as possible

## Acceptance Criteria

- [ ] When I create a new key, if I have connection(s) existing for a wallet, I can opt to add it to that connection
- [ ] There is a way to add a key to an existing connection from the connections list (i.e. give permissions)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
