### ISSUE TITLE
Disconnect all connections to this wallet, and all wallets to this dapp

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#591]
## Story

As a user
I want to disconnect all connections to this wallet 
So that I can easily limit access to my assets

## Acceptance Criteria

- [ ] There is a way to disconnect all connections to a wallet
- [ ] There is a way to disconnect all wallets from a dapp

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="1716" alt="Screenshot 2023-03-28 at 15 40 07" src="https://user-images.githubusercontent.com/46783148/228274624-baf826d4-2a24-4ea4-a91c-e79ae0f185b8.png">
