### ISSUE TITLE
Filter transactions by wallet, key

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#592]
## Story

As a user
I want to see just the transactions for a specific wallet and or a specific key
So that I can find the transaction I'm looking for

## Acceptance Criteria

- [ ] I can filter the global transactions list by wallet and by key
- [ ] I can find transactions per key from the wallet view of my keys  
- [ ] I can find transactions per wallet from the wallet view 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="1254" alt="Screenshot 2023-03-28 at 15 44 13" src="https://user-images.githubusercontent.com/46783148/228275898-43df385a-202e-490d-adae-d46bb1f78a76.png">

<img width="994" alt="Screenshot 2023-03-28 at 15 47 17" src="https://user-images.githubusercontent.com/46783148/228276821-babccf42-cc47-43c3-87fc-db1beb583765.png">
