### ISSUE TITLE
Decide to try

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#596]
Pull into the sprint for the UX and design and to lobby Matt to prioritise for Console/Goverance/Explorer teams

## Story

As a Console user
I want to understand that I need a vega wallet to use console, and why 
So that I feel confident that Vega wallet is trustworthy and can download and install the app I need quickly and easily

## Acceptance Criteria

- [ ] I can understand that I need to get Vega Wallet to use Console
- [ ] I can understand what it is / does in a way to builds trust
- [ ] I can easily get the version relevant to my OS from here

## Tasks

- [ ] Define the Vega Wallet "proposition" i.e. key points / features / usages 
- [ ] Consider what happens on Fairground Wallet vs Vega Wallet (there are other options in there right now, where does "view as" go etc.)
- [ ] Work out how this state relates to what you see when you do have a wallet (remembering there's the complication of not knowing if you have CLI or desktop app) 
- [ ] Create more detailed sketch and define content
- [ ] Review with stakeholders
- [ ] Visual Design
- [ ] Implement
- [ ] QA Test
- [ ] Release

## Sketch

<img width="2127" alt="Screenshot 2023-03-29 at 17 11 24" src="https://user-images.githubusercontent.com/46783148/228601050-b2186e81-98f1-4e58-b384-e1e881c8d404.png">
