### ISSUE TITLE
Create / improve OS installers e.g. a dmg download for mac

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#599]
## The Chore

**Refine: what if anything would be easy / quick to do? Deprioritise the rest. If nothing can be down quickly / easily then we leave it.**

Follow common OS conventions for downloaded apps (see attached) by make the download a packaged dmg with a background image with arrow and logo for mac, with an equivalent Windows, Linux experience.

<img width="1197" alt="Screenshot 2023-03-29 at 18 01 00" src="https://user-images.githubusercontent.com/46783148/228613706-2776aa72-c071-4120-8bc9-670de46298be.png">

## Acceptance criteria 

- [ ] When I download the desktop wallet app on any OS,I see the common installer experience (equivalent to MacOS screenshot)

## Tasks

- [ ] Check what happens for each prioritised OS right now
- [ ] Identify equivalent patterns required
- [ ] Design 
- [ ] Implement
- [ ] Test

## Additional details / background info

We should ship the macos application with an installer

There are decisions to make on this regarding what we need / want to do in terms of signing the bundle

## Reference
https://github.com/remko/fancy-dmg/blob/master/Makefile
