### ISSUE TITLE
SPIKE: Define the UX and understand the work involved in reducing the frequency of password requests

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#604]
## The Spike

We have open tickets that require core changes and would result in breaking changes and therefore require frontend work to be able to release. 

As there is a soft code freeze for the core (/vega) currently to minimise risk in the run up to Alpha Mainnet launch we need to get a better understanding of the improved experience we want to deliver to the user and therefore understand the level of work required in the frontend to achieve it. So that we can better assess whether we want to push to get these changes into core sooner rather than later, taking into account frontend capacity and relative priority/value compared to the other improvements we would like to make.  

## Tasks

- [x] Collaborate to build a shared understanding of the desired experience around the use of the password/phrase in the Vega wallet, the different cases for when it is needed and when it isn't and scenarios where want to persist it i.e. connections with dapps etc. 
- [x] Break down into user stories and add to github backlog (or refine existing tickets as applicable)
- [ ] Assess the work involved for both frontend and backend
- [ ] Agree as a team and put forward a proposal to core (as applicable) for what of the work we think should be done now v wait until after Alpha Mainnet launch 

## Resulting tickets refined 

- [Reduce passphrase requests through session history for admin and client endpoints (locking mechanism on wallet API) #7223
](https://github.com/vegaprotocol/vega/issues/7223)
- #635 
- [Connection tokens should survive reboot](https://github.com/vegaprotocol/vega/issues/7906)
- #636 
- #626

## Additional details / background info

Work in progress https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764550384647256&cot=14
