### ISSUE TITLE
Create wallet, password and recovery phrase

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#606]
## Story

As a user 
I want to set up my wallet app as quickly as possible
So that I can try out Console / another Vega dapp without interuption

## Acceptance Criteria

- [ ] There is a way to understand at a glance what Vega wallet does / be assured it's safe / secure (depending on outcome of #596 )
- [ ] There is a way to create a new wallet
-- [ ] Wallet name is auto generated in the background Wallet1
-- [ ] There is a visual way to understand the number of steps to complete wallet creation 
-- [ ] I can see an explanation of what the password is for (unlocking the wallet app rather than per wallet OR just for the wallet - depends on the outcome of #604 ) and that it cannot be  used to recover my wallet / recovered itself 
-- [ ] There is an indicator for password strength 
-- [ ] There is a way to submit my password 
-- [ ] I can see a 24 word pass phrase and understand what it's for
- [ ] There is a way to import an existing wallet

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
