### ISSUE TITLE
Transactions interaction

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#630]
## Story

As a wallet user
I want to see the details of the transaction that has been sent by a dapp
So that I can make a decision on whether I want to approve it or not

## Acceptance Criteria

- [ ] I can see the transaction type
- [ ] I can see which key within which wallert I am signing it with 
- [ ] I can see clearly the site that's making the request i.e. "request from" and the URL visually distinct
- [ ] There is a JSON preview of the transaction (for now) 
- [ ] I can see the network the transaction is on 
- [ ] There is a way to confirm or cancel the transaction

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

Related tickets 
* #480 
* #637 
* #638 
* #640 
* #641
