### ISSUE TITLE
Password timeout

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#636]
## Story

As a user
I want to enter my password only very occasionally and rely on the security of my computer to maintain my wallet privacy 
So that I don't have to enter my password every time I open the wallet

## Acceptance Criteria

- [ ] Only after a period of time am I required to enter my single password. We accept that a users computer security is enough rather than need users to enter their password every time they open the application 
- [ ] If session tokens have expired, user hasn't entered a password recently basically and that has timed out(?) then there is a way for the user to enter their single password to unlock the application

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by notbot00** [comment]
https://github.com/vegaprotocol/vegawallet-desktop/issues/635 has been implemented, meaning the desktop wallet won't ask for passphrases multiple times. I'm not sure if it has a timeout / we want to improve the experience by adding some sort of a lock timeout to it.
