### ISSUE TITLE
Handling multiple transaction approval requests

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#637]
## Story

As a user
I want to quickly and easily review multiple transaction requests in one go
So that interruption to my trading is minimised 

## Acceptance Criteria

- [ ] There is a warning if there are multiple approval requests 
- [ ] There is a way to let you check them all quickly / easily

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
