### ISSUE TITLE
Handling transfers transactions between keys and wallets

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#639]
## Story

As a user
I want to recognise at a scan of the transaction request whether my transfer is to one of my own keys / wallets or external known / external new
So that I know when to exercise more caution

## Acceptance Criteria

- [ ] There is a visual way to recognise / distinguish your transfer based on where you are transferring to e.g. showing different iconography if you're doing a transfer to a pubkey in your current wallet vs. a different one of your wallets vs. and external key you've sent to before vs. an unknown key

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
