### ISSUE TITLE
Highlight extreme transaction requests 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#640]
## Story

As a user
I want it made clear to me if the transaction I am carrying out is extreme in any way
So that I know to reconsider my actions

## Acceptance Criteria

- [ ] There is a system / approach to flagging extreme transactions like low/high price, large size, moving most or all of your funds
- [ ] I can see visually in the transaction flow whether the request hits one of these limits

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
