### ISSUE TITLE
Visually differentiated transactions

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#641]
## Story

As a user
I want different types of transactions to be visually distinct depending on the transaction type
So that I recognise the difference and can see that some are more dangerous / critical than others

## Acceptance Criteria

- [ ] There is a categorisation of transaction types based on danger / impact e.g. to assets / funds
- [ ] We've a visual way to present the categories in the UI

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by JonRay15** [comment]
Desktop ... wont do
