### ISSUE TITLE
Ease the transaction review to help users identify risks / problems

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#642]
## Tasks for this sprint

- [x] Review the list and decide which make sense to address now / consider in our target journey
- [x] Create tickets to sketch / design or incorporate into target experience sketches as applicable
- [ ] Circle back on our approach to these things with Barney in this thread https://vegaprotocol.slack.com/archives/C8WS7M50E/p1678277036328849?thread_ts=1678273206.383069&cid=C8WS7M50E 

UI affordances I (@barnabee) could imagine in wallet:

- highlighting the site they created a transaction with a warning of it’s not the same as the site that submitted the most recent transaction #638 
- highlighting better in the approve window the site that’s doing the request in all cases - ie separating a label like “request from” and the site “console.fairground.wtf” and making the latter more clear, it’s a bit lost in the text #630 
- highlighting with a warning if the request you are looking at is older than some number of seconds #630 
- highlighting with a warning if there are multiple approval requests and letting you check them all #637 
- showing different iconography if you’re doing a transfer to a pubkey in your current wallet vs a different one of your connected wallets vs an external key you’ve sent to before vs an unknown key, and pulling in the wallet and key names #639 
- customising messages and colours and icons depending on txn types, some are more dangerous than others #641 
- highlighting extreme values (low/high price, large size, moving most or all of your funds, etc.) #640
