### ISSUE TITLE
Upgrade to use latest wallet backend version

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#720]
## The Chore

In preparation for **Deployment 1** we need to upgrade the desktop wallet to use the latest version of the wallet backend, check and verify that it works plug and play with the new transaction types and prepare to release.

## Tasks

- [ ] Upgrade the desktop wallet to use the latest version of the wallet backend
- [ ] Add A/Cs and test coverage to ensure the following transactions work as expected:
    - [ ] Successor Markets - new transaction type supported
    - [ ] Governance Transfers - new transaction type supported
    - [ ] Stop Orders - new transaction type supported
    - [ ] Iceberg Orders  - updated order transaction supported
- [ ] Deploy to Stagnet
- [ ] Test in Stagnet
    - [ ] Run automated tests of existing functionality
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
- [ ] Deploy to Fairground
- [ ] Test in Fairground
    - [ ] Run automated tests of existing functionality
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
 - [ ] Deploy to Validator Testnet
- [ ] Test in Validator Testnet
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
- [ ] Deploy to Mainnet
 - [ ] Test in Mainnet
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
