### ISSUE TITLE
Calls to action to trade or govern (or check out other dapps) to "continue" the journey

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#729]
## Story

As a user
I want to easily go to the next step in my Vega onboarding i.e. trade, govern or explore other Vega dapps when I've set up my wallet
So that I can get "doing" as fast as possible regardless of where I started from 

## Acceptance Criteria

- [ ] There is a way to go to console from the desktop wallet i.e. a link / cta 
- [ ] There is a way to go govern from the desktop wallet i.e. a link / cta 
- [ ] There is a way to view other Vega dapps i.e. a link / cta 

## Tasks

- [ ] Detailed sketch
- [ ] UI Design inc. working out how to manage the actions should they be across app in a toolbar or something else?
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

Sketch is from the browser wallet but should be able to be applied to desktop wallet easily enough
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/5e394a94-63b3-43ba-8817-6ed660ee4f98)
